# Site settings
title: Circuit Imaging
owner: Circuit Imaging
description: > # this means to ignore newlines
    We make circuit imaging devices.
#baseurl: "/ccbautomation-website" # the subpath of your site, e.g. /blog
#url: "127.0.0.1"
url: "http://circuitimaging.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:title/

# http://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: Circuit Imaging
      comments: true
